//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickManagementSystem.Main.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BrickManagementDBEntities : DbContext
    {
        public BrickManagementDBEntities()
            : base("name=BrickManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<mstCompanyInfo> mstCompanyInfoes { get; set; }
        public virtual DbSet<tblItemInfo> tblItemInfoes { get; set; }
        public virtual DbSet<tblItemsFromStock> tblItemsFromStocks { get; set; }
        public virtual DbSet<tblRequisitionForm> tblRequisitionForms { get; set; }
        public virtual DbSet<tblStock> tblStocks { get; set; }
    }
}
