//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickManagementSystem.Main.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomingDemand
    {
        public int IncomingDemandID { get; set; }
        public Nullable<int> ReqID { get; set; }
        public string State { get; set; }
        public string Note { get; set; }
    
        public virtual tblRequisitionForm tblRequisitionForm { get; set; }
    }
}
