//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickManagementSystem.Main.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItemInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblItemInfo()
        {
            this.tblItemsFromStocks = new HashSet<tblItemsFromStock>();
        }
    
        public int ItemID { get; set; }
        public Nullable<int> ReqID { get; set; }
        public string KhataNumber { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Unit { get; set; }
        public string Remarks { get; set; }
    
        public virtual tblRequisitionForm tblRequisitionForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblItemsFromStock> tblItemsFromStocks { get; set; }
    }
}
