//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrickManagementSystem.Main.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStock
    {
        public int StockID { get; set; }
        public Nullable<int> ReqID { get; set; }
        public string RequestState { get; set; }
        public string ItemName { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> Unit { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> RespondedDate { get; set; }
    
        public virtual tblRequisitionForm tblRequisitionForm { get; set; }
    }
}
